services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 7543:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
