apiVersion: batch/v1
kind: Job
metadata:
  name: bookshelf-migrations
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: matheusinit/bookshelf:latest
          envFrom:
            - secretRef:
                name: rest-secrets
          command: 
            - "sh"
            - "-c"
            - "cd /app && /root/.local/bin/poetry run python -m app.models"
      restartPolicy: Never
