apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf-rest-deployment
  labels:
    app: bookshelf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
    spec:
      containers:
      - name: bookshelf-rest
        image: matheusinit/bookshelf:latest
        envFrom:
            - secretRef:
                name: rest-secrets
        ports:
        - containerPort: 8000